export interface Product {
    id: number;
    name: string;
    slug: string;
    price: number;
    oldPrice?: number;
    img: string;
    rating: number;
    reviews: number;
    inStock: boolean;
    category: string;
    tag: string;
    sold: number;
}

export const products: Product[] = [
    {
        id: 13,
        name: 'Smart Fitness Watch Series 6',
        slug: 'smart-fitness-watch-series-6',
        price: 4299,
        img: 'photo-1523275335684-37898b6baf30',
        rating: 4.6,
        reviews: 167,
        inStock: true,
        category: 'Electronics',
        tag: 'Best Seller',
        sold: 870,
    },
    {
        id: 12,
        name: 'Classic Leather Sneakers',
        slug: 'classic-leather-sneakers',
        price: 2999,
        oldPrice: 3999,
        img: 'photo-1542291026-7eec264c27ff',
        rating: 4.7,
        reviews: 132,
        inStock: true,
        category: 'Fashion',
        tag: '',
        sold: 760,
    },
    {
        id: 11,
        name: 'Premium Sunglasses UV400',
        slug: 'premium-sunglasses-uv400',
        price: 1599,
        img: 'photo-1572635196237-14b3f281503f',
        rating: 4.5,
        reviews: 98,
        inStock: false,
        category: 'Fashion',
        tag: '',
        sold: 540,
    },
    {
        id: 10,
        name: 'Minimalist Backpack 20L',
        slug: 'minimalist-backpack-20l',
        price: 2499,
        img: 'photo-1553062407-98eeb64c6a62',
        rating: 4.4,
        reviews: 41,
        inStock: true,
        category: 'Fashion',
        tag: 'New',
        sold: 320,
    },
    {
        id: 9,
        name: 'Ceramic Pour-Over Coffee Set',
        slug: 'ceramic-pour-over-coffee-set',
        price: 1899,
        img: 'photo-1495774856032-8b90bbb32b32',
        rating: 4.9,
        reviews: 23,
        inStock: true,
        category: 'Home & Living',
        tag: 'New',
        sold: 210,
    },
    {
        id: 8,
        name: 'Mechanical Keyboard RGB',
        slug: 'mechanical-keyboard-rgb',
        price: 5499,
        oldPrice: 6299,
        img: 'photo-1587829741301-dc798b83add3',
        rating: 4.7,
        reviews: 36,
        inStock: true,
        category: 'Electronics',
        tag: '',
        sold: 430,
    },
    {
        id: 7,
        name: 'Cotton Oversized T-Shirt',
        slug: 'cotton-oversized-t-shirt',
        price: 899,
        img: 'photo-1521572163474-6864f9cf17ab',
        rating: 4.3,
        reviews: 18,
        inStock: false,
        category: 'Fashion',
        tag: '',
        sold: 150,
    },
    {
        id: 6,
        name: 'Portable Bluetooth Speaker',
        slug: 'portable-bluetooth-speaker',
        price: 2199,
        oldPrice: 2799,
        img: 'photo-1608043152269-423dbba4e7e1',
        rating: 4.5,
        reviews: 89,
        inStock: true,
        category: 'Electronics',
        tag: '',
        sold: 620,
    },
    {
        id: 5,
        name: 'Wireless Earbuds Pro',
        slug: 'wireless-earbuds-pro',
        price: 3499,
        img: 'photo-1590658268037-6bf12165a8df',
        rating: 4.7,
        reviews: 142,
        inStock: true,
        category: 'Electronics',
        tag: 'Best Seller',
        sold: 810,
    },
    {
        id: 4,
        name: 'Scented Soy Candle Set',
        slug: 'scented-soy-candle-set',
        price: 749,
        img: 'photo-1602874801007-bd458bb1b8b6',
        rating: 4.6,
        reviews: 52,
        inStock: true,
        category: 'Home & Living',
        tag: '',
        sold: 280,
    },
    {
        id: 3,
        name: 'Matte Lipstick Collection',
        slug: 'matte-lipstick-collection',
        price: 1299,
        oldPrice: 1699,
        img: 'photo-1586495777744-4413f21062fa',
        rating: 4.4,
        reviews: 64,
        inStock: true,
        category: 'Beauty',
        tag: 'New',
        sold: 360,
    },
    {
        id: 2,
        name: 'Yoga Mat Non-Slip',
        slug: 'yoga-mat-non-slip',
        price: 1450,
        img: 'photo-1601925260368-ae2f83cf8b7f',
        rating: 4.5,
        reviews: 77,
        inStock: true,
        category: 'Sports',
        tag: '',
        sold: 290,
    },
    {
        id: 1,
        name: 'Stainless Steel Water Bottle',
        slug: 'stainless-steel-water-bottle',
        price: 999,
        img: 'photo-1602143407151-7111542de6e8',
        rating: 4.6,
        reviews: 110,
        inStock: false,
        category: 'Sports',
        tag: '',
        sold: 470,
    },
];
